apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alloy-operator-set
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - list:
              elements:
                - name: stage-cluster
                  nameNormalized: alloy-operator
                  repoURL: https://github.com/FaisalAl-Rayes/lgtmo-alloy-o11y.git
                  path: gitops/components/operators/alloy-operator
                  namespace: alloy-system
                  environment: monitoring
          - clusters:
              selector:
                matchLabels:
                  environment: monitoring
  template:
    metadata:
      name: '{{nameNormalized}}'
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: '{{name}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

