apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alloy-metrics
  namespace: alloy-system
  labels:
    app: alloy-metrics
spec:
  serviceName: alloy-metrics
  replicas: 1
  selector:
    matchLabels:
      app: alloy-metrics
  template:
    metadata:
      labels:
        app: alloy-metrics
    spec:
      serviceAccountName: alloy-metrics
      containers:
        - name: alloy
          image: grafana/alloy:v1.0.0
          args:
            - run
            - /etc/alloy/config.alloy
            - --storage.path=/var/lib/alloy/data
            - --server.http.listen-addr=0.0.0.0:12345
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MIMIR_ENDPOINT
              value: "PLACEHOLDER_MIMIR_ENDPOINT"
            - name: ENVIRONMENT
              value: "default"
          ports:
            - name: http-metrics
              containerPort: 12345
              protocol: TCP
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: data
              mountPath: /var/lib/alloy/data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: alloy-metrics-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy-metrics
  namespace: alloy-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy-metrics
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alloy-metrics
subjects:
  - kind: ServiceAccount
    name: alloy-metrics
    namespace: alloy-system

