apiVersion: v1
kind: Service
metadata:
  name: alloy-metrics
  namespace: alloy-system
  labels:
    app: alloy-metrics
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 12345
      targetPort: 12345
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
  selector:
    app: alloy-metrics

