apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - grafana-datasources.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-ingress.yaml

