apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: monitoring
  labels:
    app: mimir
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9009
      targetPort: 9009
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: 9095
      protocol: TCP
  selector:
    app: mimir

