apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-otel-instrumented-app
spec:
  template:
    spec:
      containers:
        - name: app
          image: quay.io/falrayes/full-otel-instrumented-app:stage-latest
          env:
            - name: ENVIRONMENT
              value: "stage"
            - name: OTEL_SERVICE_NAME
              value: "full-otel-instrumented-app-stage"

