apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: monitoring
type: Opaque
stringData:
  root-user: minio
  root-password: minio123
  # S3-compatible credentials for Loki
  access-key-id: minio
  secret-access-key: minio123

