apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webapps-set
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - list:
              elements:
                - name: stage-cluster
                  nameNormalized: full-otel-instrumented-app
                  repoURL: https://github.com/FaisalAl-Rayes/lgtmo-alloy-o11y.git
                  path: gitops/components/full-otel-instrumented-app/overlays/stage
                  namespace: full-otel-instrumented-app-ns
                  environment: stage
                - name: stage-cluster
                  nameNormalized: prom-otel-instrumented-app
                  repoURL: https://github.com/FaisalAl-Rayes/lgtmo-alloy-o11y.git
                  path: gitops/components/prom-otel-instrumented-app/overlays/stage
                  namespace: prom-otel-instrumented-app-ns
                  environment: stage
          - clusters:
              selector:
                matchLabels:
                  environment: stage
  template:
    metadata:
      name: '{{nameNormalized}}-{{environment}}'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: '{{name}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
