apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: grafanaagents.monitoring.grafana.com
spec:
  group: monitoring.grafana.com
  names:
    kind: GrafanaAgent
    listKind: GrafanaAgentList
    plural: grafanaagents
    singular: grafanaagent
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}

