apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alloy-system

resources:
  - namespace.yaml

helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: 0.9.2
    releaseName: alloy-operator
    namespace: alloy-system
    includeCRDs: true
    valuesInline:
      clustering:
        enabled: true
      controller:
        replicas: 3
        enableStatefulSetAutoDeletePVC: false
