apiVersion: v1
kind: Service
metadata:
  name: full-otel-instrumented-app
  labels:
    app: full-otel-instrumented-app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: full-otel-instrumented-app
