apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alloy-system

resources:
  - ../../base

patches:
  - path: patches/alloy-alerts-endpoints.yaml
    target:
      kind: Alloy
      name: alloy-alerts

