apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rules-logs
  namespace: monitoring
data:
  logs-alerts.yaml: |
    groups:
      - name: logs-alerts
        interval: 1m
        rules:
          # High Error Log Rate
          - alert: HighErrorLogRate
            expr: |
              sum by (tenant, app) (rate({level="error"}[5m])) > 10
            for: 5m
            labels:
              severity: warning
              source: loki
              type: logs
            annotations:
              summary: "High error log rate for {{ $labels.app }} (tenant: {{ $labels.tenant }})"
              description: "Error log rate is {{ $value }} logs/s"
          
          # Critical Error in Logs
          - alert: CriticalErrorInLogs
            expr: |
              sum by (tenant, app) (rate({level="critical"}[1m])) > 0
            for: 1m
            labels:
              severity: critical
              source: loki
              type: logs
            annotations:
              summary: "Critical errors detected in {{ $labels.app }} (tenant: {{ $labels.tenant }})"
              description: "Critical log rate: {{ $value }} logs/s"
          
          # Application Panic/Crash Pattern
          - alert: ApplicationPanic
            expr: |
              sum by (tenant, app) (count_over_time({app=~".+"} |~ "(?i)(panic|fatal|crashed|out of memory)" [5m])) > 0
            for: 1m
            labels:
              severity: critical
              source: loki
              type: logs
            annotations:
              summary: "Application panic detected in {{ $labels.app }} (tenant: {{ $labels.tenant }})"
              description: "Found {{ $value }} panic/crash messages in logs"
          
          # Authentication Failures
          - alert: HighAuthenticationFailureRate
            expr: |
              sum by (tenant, app) (rate({app=~".+"} |~ "(?i)(authentication failed|login failed|unauthorized)" [5m])) > 5
            for: 5m
            labels:
              severity: warning
              source: loki
              type: logs
            annotations:
              summary: "High authentication failure rate for {{ $labels.app }} (tenant: {{ $labels.tenant }})"
              description: "Authentication failures: {{ $value }} failures/s"
          
          # Database Connection Errors
          - alert: DatabaseConnectionErrors
            expr: |
              sum by (tenant, app) (count_over_time({app=~".+"} |~ "(?i)(database connection|connection refused|connection timeout)" [5m])) > 10
            for: 3m
            labels:
              severity: critical
              source: loki
              type: logs
            annotations:
              summary: "Database connection errors in {{ $labels.app }} (tenant: {{ $labels.tenant }})"
              description: "Found {{ $value }} database connection errors"
          
          # No Logs Received (Application Down?)
          - alert: NoLogsReceived
            expr: |
              sum by (tenant, app) (count_over_time({app=~".+"}[5m])) == 0
            for: 10m
            labels:
              severity: warning
              source: loki
              type: logs
            annotations:
              summary: "No logs received from {{ $labels.app }} (tenant: {{ $labels.tenant }})"
              description: "Application may be down or logging is broken"

