apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-rules-traces
  namespace: monitoring
data:
  traces-alerts.yaml: |
    groups:
      - name: traces-alerts
        interval: 1m
        rules:
          # High Trace Error Rate
          # Note: This assumes you're exporting trace metrics from Tempo
          - alert: HighTraceErrorRate
            expr: |
              (sum by (tenant, service_name) (rate(traces_spanmetrics_calls_total{status_code="STATUS_CODE_ERROR"}[5m]))
              /
              sum by (tenant, service_name) (rate(traces_spanmetrics_calls_total[5m]))) * 100 > 5
            for: 5m
            labels:
              severity: warning
              source: tempo
              type: traces
            annotations:
              summary: "High trace error rate for {{ $labels.service_name }} (tenant: {{ $labels.tenant }})"
              description: "Trace error rate is {{ $value }}%"
          
          # Slow Traces (High Latency)
          - alert: HighTraceLatency
            expr: |
              histogram_quantile(0.95, 
                sum by (tenant, service_name, le) (
                  rate(traces_spanmetrics_latency_bucket[5m])
                )
              ) > 1000
            for: 5m
            labels:
              severity: warning
              source: tempo
              type: traces
            annotations:
              summary: "High latency detected for {{ $labels.service_name }} (tenant: {{ $labels.tenant }})"
              description: "P95 latency is {{ $value }}ms (threshold: 1000ms)"
          
          # Service Dependency Failure
          - alert: ServiceDependencyFailure
            expr: |
              sum by (tenant, service_name, span_name) (
                rate(traces_spanmetrics_calls_total{status_code="STATUS_CODE_ERROR", span_kind="SPAN_KIND_CLIENT"}[5m])
              ) > 0.1
            for: 3m
            labels:
              severity: critical
              source: tempo
              type: traces
            annotations:
              summary: "Service dependency failure: {{ $labels.service_name }} -> {{ $labels.span_name }} (tenant: {{ $labels.tenant }})"
              description: "Downstream call failures: {{ $value }} calls/s"
          
          # Database Query Performance
          - alert: SlowDatabaseQueries
            expr: |
              histogram_quantile(0.95,
                sum by (tenant, service_name, span_name, le) (
                  rate(traces_spanmetrics_latency_bucket{span_kind="SPAN_KIND_CLIENT", db_system=~".+"}[5m])
                )
              ) > 500
            for: 5m
            labels:
              severity: warning
              source: tempo
              type: traces
            annotations:
              summary: "Slow database queries in {{ $labels.service_name }} (tenant: {{ $labels.tenant }})"
              description: "P95 DB query latency: {{ $value }}ms for {{ $labels.span_name }}"

