apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-otel-instrumented-app
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: app
          image: quay.io/falrayes/full-otel-instrumented-app:prod-latest
          env:
            - name: ENVIRONMENT
              value: "prod"
            - name: OTEL_SERVICE_NAME
              value: "full-otel-instrumented-app-prod"

