apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alerting-rules
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FaisalAl-Rayes/lgtmo-alloy-o11y.git
    targetRevision: HEAD
    path: gitops/components/alerting-rules/base
  destination:
    name: monitoring-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

