apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alloy-agents
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # Alloy Agent for stage cluster
          - cluster: stage-cluster
            name: alloy-agent-stage
            path: gitops/components/alloy-agent/overlays/stage
            namespace: alloy-system
            environment: stage
          # Alloy Agent for prod cluster
          - cluster: prod-cluster
            name: alloy-agent-prod
            path: gitops/components/alloy-agent/overlays/prod
            namespace: alloy-system
            environment: prod
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/YOUR_USERNAME/YOUR_REPO.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

