apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: instrumented-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # App in stage cluster
          - cluster: stage-cluster
            name: instrumented-app-stage
            path: gitops/components/instrumented-app/overlays/stage
            namespace: apps-stage
            environment: stage
          # App in prod cluster
          - cluster: prod-cluster
            name: instrumented-app-prod
            path: gitops/components/instrumented-app/overlays/prod
            namespace: apps-prod
            environment: prod
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/FaisalAl-Rayes/lgtmo-alloy-o11y.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

