apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app
  namespace: argocd
spec:
  source:
    path: gitops/components/go-webapp/overlays/prod

  destination:
    name: prod-cluster
    namespace: prod-go
