apiVersion: v1
kind: Service
metadata:
  name: prom-otel-instrumented-app
  labels:
    app: prom-otel-instrumented-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: prom-otel-instrumented-app
