apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  name: prom-otel-instrumented-app-podlogs
  labels:
    app: prom-otel-instrumented-app
spec:
  selector:
    matchLabels:
      app: prom-otel-instrumented-app
  relabelings:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node_name
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_container_name]
      targetLabel: container

