apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-otel-instrumented-app
  labels:
    app: prom-otel-instrumented-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prom-otel-instrumented-app
  template:
    metadata:
      labels:
        app: prom-otel-instrumented-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: app
          image: quay.io/falrayes/prom-otel-instrumented-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "http://alloy-traces.alloy-system.svc.cluster.local:4317"
            - name: OTEL_SERVICE_NAME
              value: "prom-otel-instrumented-app"
            - name: ENVIRONMENT
              value: "default"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=prom-otel-instrumented-app,deployment.environment=$(ENVIRONMENT)"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 20
          #   periodSeconds: 5

