apiVersion: v1
kind: Service
metadata:
  name: loki-nodeport-prod
  namespace: monitoring
  labels:
    app: loki
    environment: monitoring
spec:
  type: NodePort
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      nodePort: 30101
      protocol: TCP
  selector:
    app: loki
    environment: monitoring

