apiVersion: v1
kind: Service
metadata:
  name: mimir-nodeport
  namespace: monitoring
  labels:
    app: mimir
    environment: stage
spec:
  type: NodePort
  ports:
    - name: http
      port: 9009
      targetPort: 9009
      nodePort: 30090
      protocol: TCP
  selector:
    app: mimir
    environment: stage

