apiVersion: v1
kind: Service
metadata:
  name: loki-nodeport
  namespace: monitoring
  labels:
    app: loki
    environment: stage
spec:
  type: NodePort
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      nodePort: 30100
      protocol: TCP
  selector:
    app: loki
    environment: stage

